apiVersion: v1
kind: Pod
metadata:
  name: test-mount
  namespace: kube-system
spec:
  hostPID: true
  hostNetwork: true
  nodeSelector:
    workload-type: jenkins-controller
  tolerations:
  - key: workload-type
    value: jenkins-controller
    effect: NoSchedule
  containers:
  - name: tester
    image: alpine:latest
    command:
    - /bin/sh
    - -c
    - |
      #!/bin/sh
      echo "Testing EFS mount from host..."
      nsenter -t 1 -m -u -i -n -p -- bash -c "
        mkdir -p /mnt/efs-test
        mount -t nfs4 -o nfsvers=4.1 fs-095eed9d5c8fcb1b9.efs.us-west-2.amazonaws.com:/ /mnt/efs-test
        echo 'Mount result: $?'
        df -h | grep efs
        umount /mnt/efs-test || true
      "
      sleep infinity
    securityContext:
      privileged: true
  restartPolicy: Never
