apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/peterboddev/eks_jenkins_central_api_gw_app_ekses.git
    targetRevision: main
    path: deploy/nginx-api
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
